# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: Operator on CRC tests

on:
  workflow_dispatch:

jobs:
  setup-test on crc:
    name: deploy operator tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download LS repository
      run: git clone https://github.com/IBM/ibm-licensing-operator.git

    - name: Download binaries
      run: |
        wget https://github.com/operator-framework/operator-sdk/releases/download/v0.17.0/operator-sdk-v0.17.0-x86_64-linux-gnu
        wget https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.16.0/crc-linux-amd64.tar.xz
        tar -xvf crc-linux-amd64.tar.xz
        mv ./operator-sdk-v0.17.0-x86_64-linux-gnu ./operator-sdk
        
        chmod +x ./operator-sdk
        ls
        cd crc-linux-amd64        
        
        
        
#    - name: Test Operator
#      run: |
#        chmod +x ./tests.sh
#        cd ./ibm-licensing-operator/
#        ./../tests.sh  2>&1 ./../test_logs.txt 
#        2>&1 | tee ./../test_logs.txt 
       
    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: operator results
        path: ./*.txt
