# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: Operator on CRC tests

on:
  workflow_dispatch:
env:
  CRC: ${{ secrets.CRC }}
  LOGIN: ${{ secrets.LOGIN }}  
  REGCRED: ${{ secrets.REGCRED }}
  PASSWORD: ${{ secrets.PASSWORD }} 
jobs:
  crc_test:
    name: deploy operator tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download LS repository
      run: git clone https://github.com/IBM/ibm-licensing-operator.git

    - name: Download binaries
      run: |
        docker login ${LOGIN}
        docker pull registry.redhat.io/openshift4/ose-service-ca-operator:latest
        ls -lrt  ~/.docker/config.json
        
        
        
        curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.9.0/kind-$(uname)-amd64"
        chmod +x ./kind
        ./kind create cluster --image kindest/node:v1.17.2 --name test
        ./kind get clusters
        kubectl config get-contexts
        kubectl config set-context kind-test
        kubectl get pods --all-namespaces
        kubectl get nodes
        sleep 60
        kubectl get pods --all-namespaces
        kubectl get nodes
        gpg --quiet --batch --yes --decrypt --passphrase="$PASSWORD" --output ./a.yaml rh_secret.yaml.gpg
        kubectl apply -f ./a.yaml
        
        ./kind load docker-image registry.redhat.io/openshift4/ose-service-ca-operator:latest  --name test
        sleep 60
        kubectl apply -f ./pod.yaml
        kubectl describe pod myocp
        sleep 30
        kubectl get pods --all-namespaces
        kubectl get nodes
        kubectl describe pod myocp
        sleep 30
        kubectl get pods --all-namespaces
        kubectl get nodes
        kubectl describe pod myocp
        sleep 30
        kubectl get pods --all-namespaces
        kubectl get nodes
        kubectl describe pod myocp
        sleep 30
        kubectl get pods --all-namespaces
        kubectl get nodes
        kubectl describe pod myocp
        sleep 30
        kubectl get pods --all-namespaces
        kubectl get nodes
        kubectl describe pod myocp
        sleep 30
        kubectl get pods --all-namespaces
        kubectl get nodes
        kubectl describe pod myocp
        sleep 30
        kubectl get pods --all-namespaces
        kubectl get nodes
        kubectl describe pod myocp
        
#    - name: Test Operator
#      run: |
#        chmod +x ./tests.sh
#        cd ./ibm-licensing-operator/
#        ./../tests.sh  2>&1 ./../test_logs.txt 
#        2>&1 | tee ./../test_logs.txt 
       
