# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: Build and Deploy to IKS

on:
  workflow_dispatch:
    inputs:
      iks_name:
        description: 'iks cluster name'
        required: false
  pull_request:

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-de
  IKS_CLUSTER: license-service

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        echo  ${{ github.event.inputs.iks_name }}
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry
        echo $IKS_CLUSTER$RANDOM > ./clustername.txt

    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
        ibmcloud cr region-set "${IBM_CLOUD_REGION}"
        ibmcloud cr login

    - name: Create K8s
      run: |
        echo  ${{ github.event.inputs.iks_name }}
        chmod 755 ./start_iks.sh
        /bin/bash ./start_iks.sh ${{ github.event.inputs.iks_name }}

    # Deploy the  to the IKS cluster
    - name: Deploy to IKS
      run: |
        kubectl get pods --all-namespaces

    - name: Remove IKS
      if: github.event.inputs.iks_name  == '' && always()
      run: |
        export CN=`cat ./clustername.txt`
        echo "REMOVE IT"
        ibmcloud ks cluster rm  --cluster $CN -f
        
    - name: Remove data from IKS
      if: github.event.inputs.iks_name  != '' && always()
      run: |
        kubectl delete namespace ibm-common-services
        
